/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


int *
fatorial_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	int fat, n;
	n = argp->x;

	// printf("Debug: n = %d\n", n);
	
	for(fat = 1; n > 1; n = n - 1){
		fat = fat * n;
	}

	printf("Fatorial: fatorial(%d) = %d\n", n, fat);
	return &result;
}

int *
modulo_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	int a = argp->x;
	int b = argp->y;
	int resultado_modulo = (a % b);
	printf("Modulo: %d %% %d = %d\n", a, b, resultado_modulo);
	return &result;
}

int *
max_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int a = argp->x;
	int b = argp->y;
	int resultado_max;

	if (a >= b) {
		resultado_max = a;
	} else {
		resultado_max = b;
	}

	printf("Max: max(%d, %d) = %d\n", a, b, resultado_max);
	return &result;
}

int *
soma_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int a = argp->x;
	int b = argp->y;
	int resultado_soma = (a + b);
	printf("Soma: %d + %d = %d\n", a, b, resultado_soma);
	return &result;
}

int *
subtracao_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int a = argp->x;
	int b = argp->y;
	int resultado_subtracao = (a - b);
	printf("Subtração: %d - %d = %d\n", a, b, resultado_subtracao);
	return &result;
}

int *
devisao_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	int a = argp->x;
	int b = argp->y;
	float resultado_divisao = a / b;
	printf("Divisão: %d / %d = %f\n", a, b, resultado_divisao);
	return &result;
}

int *
multiplicacao_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	int a = argp->x;
	int b = argp->y;
	int resultado_multiplicacao = (a * b);
	printf("Multiplicação: %d * %d = %d\n", a, b, resultado_multiplicacao);
	return &result;
}
