/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operands {
	int x;
	int y;
};
typedef struct operands operands;

#define SIMP_PROG 0x2fffffff
#define SIMP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define fatorial 1
extern  int * fatorial_1(operands *, CLIENT *);
extern  int * fatorial_1_svc(operands *, struct svc_req *);
#define modulo 2
extern  int * modulo_1(operands *, CLIENT *);
extern  int * modulo_1_svc(operands *, struct svc_req *);
#define max 3
extern  int * max_1(operands *, CLIENT *);
extern  int * max_1_svc(operands *, struct svc_req *);
#define soma 4
extern  int * soma_1(operands *, CLIENT *);
extern  int * soma_1_svc(operands *, struct svc_req *);
#define subtracao 5
extern  int * subtracao_1(operands *, CLIENT *);
extern  int * subtracao_1_svc(operands *, struct svc_req *);
#define devisao 6
extern  int * devisao_1(operands *, CLIENT *);
extern  int * devisao_1_svc(operands *, struct svc_req *);
#define multiplicacao 7
extern  int * multiplicacao_1(operands *, CLIENT *);
extern  int * multiplicacao_1_svc(operands *, struct svc_req *);
extern int simp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define fatorial 1
extern  int * fatorial_1();
extern  int * fatorial_1_svc();
#define modulo 2
extern  int * modulo_1();
extern  int * modulo_1_svc();
#define max 3
extern  int * max_1();
extern  int * max_1_svc();
#define soma 4
extern  int * soma_1();
extern  int * soma_1_svc();
#define subtracao 5
extern  int * subtracao_1();
extern  int * subtracao_1_svc();
#define devisao 6
extern  int * devisao_1();
extern  int * devisao_1_svc();
#define multiplicacao 7
extern  int * multiplicacao_1();
extern  int * multiplicacao_1_svc();
extern int simp_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operands (XDR *, operands*);

#else /* K&R C */
extern bool_t xdr_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
